# Generated by Django 6.0.7 on 2026-08-03 18:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False, help_text='Whether this record has reached the central server.')),
                ('origin_clinic_id', models.UUIDField(blank=True, help_text='Identifies the source clinic in multi-clinic deployments.', null=True)),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(help_text='e.g. tablet, ml, vial', max_length=30)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Low-stock alert triggers at or below this quantity.')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False, help_text='Whether this record has reached the central server.')),
                ('origin_clinic_id', models.UUIDField(blank=True, help_text='Identifies the source clinic in multi-clinic deployments.', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('insurance', 'Insurance')], max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False, help_text='Whether this record has reached the central server.')),
                ('origin_clinic_id', models.UUIDField(blank=True, help_text='Identifies the source clinic in multi-clinic deployments.', null=True)),
                ('description', models.CharField(help_text='e.g. Consultation fee, Amoxicillin, Malaria test', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False, help_text='Whether this record has reached the central server.')),
                ('origin_clinic_id', models.UUIDField(blank=True, help_text='Identifies the source clinic in multi-clinic deployments.', null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('estimated_age', models.PositiveIntegerField(blank=True, help_text='Used when the patient does not know their exact date of birth.', null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(blank=True, help_text='Used for SMS appointment reminders.', max_length=20)),
                ('village', models.CharField(blank=True, max_length=150)),
                ('parish', models.CharField(blank=True, max_length=150)),
                ('district', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20)),
                ('patient_card_no', models.CharField(blank=True, help_text='Clinic-issued card number, printed for the patient on first visit.', max_length=50, null=True, unique=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='core_patien_full_na_9fef03_idx'), models.Index(fields=['phone_number'], name='core_patien_phone_n_883315_idx'), models.Index(fields=['patient_card_no'], name='core_patien_patient_3e395f_idx')],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.patient'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False, help_text='Whether this record has reached the central server.')),
                ('origin_clinic_id', models.UUIDField(blank=True, help_text='Identifies the source clinic in multi-clinic deployments.', null=True)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('clinical_officer', 'Clinical Officer'), ('pharmacist', 'Pharmacist'), ('receptionist', 'Receptionist'), ('lab_technician', 'Lab Technician'), ('admin', 'Admin / In-charge')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck instead of deleting, to preserve visit/prescription history.')),
                ('user', models.OneToOneField(blank=True, help_text="Login account for this staff member. Django's built-in auth handles password hashing, so no raw password field is stored here.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False, help_text='Whether this record has reached the central server.')),
                ('origin_clinic_id', models.UUIDField(blank=True, help_text='Identifies the source clinic in multi-clinic deployments.', null=True)),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit_type', models.CharField(choices=[('outpatient', 'Outpatient'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('antenatal', 'Antenatal')], default='outpatient', max_length=20)),
                ('chief_complaint', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('vitals', models.JSONField(blank=True, default=dict, help_text='e.g. BP, temperature, weight, pulse')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('referred', 'Referred')], default='open', max_length=10)),
                ('attending_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_visits', to='core.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False, help_text='Whether this record has reached the central server.')),
                ('origin_clinic_id', models.UUIDField(blank=True, help_text='Identifies the source clinic in multi-clinic deployments.', null=True)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration_days', models.PositiveIntegerField()),
                ('quantity_dispensed', models.PositiveIntegerField(default=0, help_text='Supports partial dispensing (UR-14).')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='core.drug')),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to='core.staff')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False, help_text='Whether this record has reached the central server.')),
                ('origin_clinic_id', models.UUIDField(blank=True, help_text='Identifies the source clinic in multi-clinic deployments.', null=True)),
                ('test_name', models.CharField(max_length=150)),
                ('result', models.TextField(blank=True)),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='core.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.visit'),
        ),
    ]
