# Generated by Django 6.0.7 on 2026-08-06 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False, help_text='Whether this record has reached the central server.')),
                ('origin_clinic_id', models.UUIDField(blank=True, help_text='Identifies the source clinic in multi-clinic deployments.', null=True)),
                ('movement_type', models.CharField(choices=[('dispense', 'Dispense'), ('restock', 'Restock'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Absolute quantity moved.')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('balance_after', models.PositiveIntegerField(help_text='Stock level of the drug immediately after this movement.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='prescription',
            name='quantity_prescribed',
            field=models.PositiveIntegerField(default=0, help_text='Total quantity the clinician prescribed for this course.'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['created_at'], name='core_prescr_created_f84290_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['quantity_dispensed'], name='core_prescr_quantit_755d27_idx'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.drug'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='prescription',
            field=models.ForeignKey(blank=True, help_text='Populated when this movement was a dispensing event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.prescription'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Staff member who performed the movement (audit trail).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.staff'),
        ),
    ]
