# Generated by Django 6.0.7 on 2026-08-06 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stockmovement_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False, help_text='Whether this record has reached the central server.')),
                ('origin_clinic_id', models.UUIDField(blank=True, help_text='Identifies the source clinic in multi-clinic deployments.', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('insurance', 'Insurance')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='e.g. MTN transaction ID, receipt number, or note.', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who generated the invoice (audit trail, SDD §8).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to='core.staff'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Human-readable invoice number, e.g. INV-2026-0001 (UR-17).', max_length=30, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='core_invoic_invoice_aef6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_status'], name='core_invoic_payment_44d952_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='core_invoic_created_da77aa_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Staff member who recorded the payment (audit trail, SDD §8).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to='core.staff'),
        ),
    ]
