# Generated by Django 6.0.7 on 2026-08-06 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_payment_alter_invoice_options_invoice_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False, help_text='Whether this record has reached the central server.')),
                ('origin_clinic_id', models.UUIDField(blank=True, help_text='Identifies the source clinic in multi-clinic deployments.', null=True)),
                ('appointment_date', models.DateTimeField()),
                ('reason', models.CharField(blank=True, help_text='e.g. Follow-up for malaria treatment review.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('reminded', 'Reminded'), ('attended', 'Attended'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.patient')),
                ('scheduled_by', models.ForeignKey(blank=True, help_text='Staff member who created the appointment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_appointments', to='core.staff')),
                ('visit', models.ForeignKey(blank=True, help_text='The visit this follow-up appointment was scheduled from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.visit')),
            ],
            options={
                'ordering': ['appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='SMSReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False, help_text='Whether this record has reached the central server.')),
                ('origin_clinic_id', models.UUIDField(blank=True, help_text='Identifies the source clinic in multi-clinic deployments.', null=True)),
                ('phone_number', models.CharField(help_text="Recipient phone number (patient's registered number).", max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(default='pending', help_text='pending, sent, failed', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, help_text="Africa's Talking message ID.", max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_reminders', to='core.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date'], name='core_appoin_appoint_5d7cff_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='core_appoin_status_e978b8_idx'),
        ),
    ]
