# Generated by Django 6.0.7 on 2026-09-08 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appointment_smsreminder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectDispense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False, help_text='Whether this record has reached the central server.')),
                ('origin_clinic_id', models.UUIDField(blank=True, help_text='Identifies the source clinic in multi-clinic deployments.', null=True)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity handed to the patient.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Drug unit price snapshotted at dispense time.', max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('dispensed_by', models.ForeignKey(blank=True, help_text='Pharmacy staff member who dispensed (audit trail).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_dispenses', to='core.staff')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_dispenses', to='core.drug')),
                ('patient', models.ForeignKey(help_text='Registered patient collecting the medication.', on_delete=django.db.models.deletion.PROTECT, related_name='direct_dispenses', to='core.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_direct_created_8aa70d_idx')],
            },
        ),
    ]
