"""
Django settings for clinic_system project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a local .env file if present (dev convenience).
# In Docker, env vars are supplied by docker-compose instead.
load_dotenv(BASE_DIR / ".env")


def _bool_env(name, default="False"):
    return os.getenv(name, default).strip().lower() in ("1", "true", "yes", "on")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-(n+^9rl#tbg0z33_sgz842+$*9-22_d6+re$g2m%3%lp5ey*-7",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _bool_env("DJANGO_DEBUG", "True")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clinic_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clinic_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Defaults to SQLite for quick local/dev use. Set DB_ENGINE=postgresql
# (or run via docker-compose, which sets this automatically) to use
# PostgreSQL instead.

if os.getenv("DB_ENGINE", "sqlite3") == "postgresql":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("DB_NAME", "clinic_system"),
            'USER': os.getenv("DB_USER", "clinic_user"),
            'PASSWORD': os.getenv("DB_PASSWORD", "clinic_password"),
            'HOST': os.getenv("DB_HOST", "db"),
            'PORT': os.getenv("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Authentication / RBAC (UR-10, UR-20, FR-9)
# https://docs.djangoproject.com/en/6.0/topics/auth/default/

# The default ModelBackend treats "correct password, inactive account" and
# "wrong password" identically, both surfacing as a generic invalid-login
# error -- so a deactivated staff member gets no useful signal. Given the
# high staff turnover this system is designed for (per UR document,
# section 2), staff need a clear "see your administrator" message instead
# of a dead end. AllowAllUsersModelBackend still checks the password first;
# it only changes what happens *after* the password is confirmed correct,
# letting AuthenticationForm's own is_active check produce the clearer
# "inactive" error defined in accounts.forms.StaffLoginForm.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.AllowAllUsersModelBackend',
]

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'accounts:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'

# UR-10: staff on a shared clinic device shouldn't need a long login
# process each time they pick the device back up during their shift, but
# NFR-5 (data protection) means sessions still shouldn't linger forever.
# A session lasts one working shift and extends on activity; it does not
# persist after the browser is fully closed.
SESSION_COOKIE_AGE = 8 * 60 * 60  # 8 hours
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Africa's Talking SMS integration (UR-24 / FR-10 / SDD 6.6)
# Set AT_API_KEY in the environment (or .env) to enable real SMS sending.
# Without it, the app runs in simulated mode (messages are logged, not sent).
AT_API_KEY = os.getenv("AT_API_KEY", "")
AT_USERNAME = os.getenv("AT_USERNAME", "sandbox")
CLINIC_NAME = os.getenv("CLINIC_NAME", "Community Health Clinic")

# Billing configuration (UR-15 / FR-7)
CONSULTATION_FEE = 5000  # UGX
LAB_TEST_FEE = 3000  # UGX
